def tisk_hlavicky():
   print("===============")
   print("=== Šibenice ===")
   print("===============")

def tisk_faze_sibenice(pocet_chyb):
   if pocet_chyb == 0:
       print("  ___________")
       print(" |/         |")
       print(" |")
       print(" |")
       print(" |")
       print(" |")
       print("_|_")
   elif pocet_chyb == 1:
       print("  ___________")
       print(" |/         |")
       print(" |         (_)")
       print(" |")
       print(" |")
       print(" |")
       print("_|_")
   elif pocet_chyb == 2:
       print("  ___________")
       print(" |/         |")
       print(" |         (_)")
       print(" |          |")
       print(" |")
       print(" |")
       print("_|_")
   elif pocet_chyb == 3:
       print("  ___________")
       print(" |/         |")
       print(" |         (_)")
       print(" |          |/")
       print(" |")
       print(" |")
       print("_|_")
   elif pocet_chyb == 4:
       print("  ___________")
       print(" |/         |")
       print(" |         (_)")
       print(" |         \|/")
       print(" |")
       print(" |")
       print("_|_")
   elif pocet_chyb == 5:
       print("  ___________")
       print(" |/         |")
       print(" |         (_)")
       print(" |         \|/")
       print(" |          |")
       print(" |")
       print("_|_")
   else:
       print("  ___________")
       print(" |/         |")
       print(" |         (_)")
       print(" |         \|/")
       print(" |          |")
       print(" |         / \\")
       print("_|_")